version: '3.2'
services:
  localstack:
    image: minio/minio:latest
    container_name: aws-s3
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_KEY}
    command: 
      server /date
    #volumes:
    #  - './.localstack:/tmp/localstack'
    #  - '/var/run/docker.sock:/var/run/docker.sock'