version: '3'
services:
    sftp:
        image: atmoz/sftp
        #volumes:
        #    - <host-dir>/upload:/home/foo/upload
        ports:
            - "2222:22"
        command: ftpuser:ftppass:::0
        networks:
            - A
    database:
        container_name: pg_mlflow
        image: postgres:13
        environment:
            - POSTGRES_USER=pgsql
            - POSTGRES_PASSWORD=pg_password
            - POSTGRES_DB=mlflow
        networks:
            - A
    tracker:
        container_name: tracker_mlflow
        image: tracker_ml
        build:
            context: ./mlflow
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks:
            - A

        entrypoint: mlflow server --default-artifact-root sftp://ftpuser:ftppass@localhost:2222 -h 0.0.0.0
networks:
    A:
        driver: bridge