name: Docker Compose Actions Workflow
on: push
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose config
      - name: Test
        run: docker-compose up -d --build
